name: Windows RDP via Tailscale
on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    steps:
    - name: Install Tailscale
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/i tailscale.msi /quiet'

    - name: Connect to Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname github-rdp

    - name: Enable RDP
      run: |
        net user rdpuser P@ssw0rd123 /add
        net localgroup administrators rdpuser /add
        reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Show Tailscale IP
      id: tsip
      run: |
        $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip
        echo "Tailscale IP: $ip"
        echo "ip=$ip" >> $env:GITHUB_OUTPUT

    - name: Save IP as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tailscale-ip
        path: ${{ steps.tsip.outputs.ip }}
